---
# Source: trivy/templates/trivy/trivy-ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: trivy
  name: trivy
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
# Source: trivy/templates/trivy/trivy-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-trivy
  namespace: trivy
  labels:
    heritage: Helm
    release: app
    chart: trivy
    app: "app-trivy"
type: Opaque
data:
  redisURL: cmVkaXM6Ly9hcHAtdHJpdnktcmVkaXM6NjM3OS9yZWRpcy81P2lkbGVfdGltZW91dF9zZWNvbmRzPTMw
  gitHubToken: ""
---
# Source: trivy/templates/nginx/reverseProxy-srv.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: trivy
spec:
  selector:
    release: app
    app: "app-trivy"
    component: nginx
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
  clusterIP: 10.43.114.232
---
# Source: trivy/templates/redis/redis-srv.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-trivy-redis
  namespace: trivy
  labels:
    heritage: Helm
    release: app
    chart: trivy
    app: "app-trivy"
spec:
  ports:
    - port: 6379
  selector:
    release: app
    app: "app-trivy"
    component: redis
---
# Source: trivy/templates/trivy/trivy-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "app-trivy"
  namespace: trivy
  labels:
    heritage: Helm
    release: app
    chart: trivy
    app: "app-trivy"
spec:
  ports:
    - name: http-trivy
      protocol: TCP
      port: 8080
  selector:
    release: app
    app: "app-trivy"
    component: trivy
---
# Source: trivy/templates/nginx/reverseProxy-dpl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: trivy
  labels:
    app: nginx-trivy
spec:
  replicas: 1
  selector:
    matchLabels:
      release: app
      app: "app-trivy"
      component: nginx
  template:
    metadata:
      labels:
        heritage: Helm
        release: app
        chart: trivy
        app: "app-trivy"
        component: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.12-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  80
          protocol: TCP
        env:
        - name: TZ
          value: Europe/Moscow
---
# Source: trivy/templates/redis/redis-sts.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-trivy-redis
  namespace: trivy
  labels:
    heritage: Helm
    release: app
    chart: trivy
    app: "app-trivy"
    component: redis
spec:
  replicas: 1
  serviceName: app-trivy-redis
  selector:
    matchLabels:
      release: app
      app: "app-trivy"
      component: redis
  template:
    metadata:
      labels:
        heritage: Helm
        release: app
        chart: trivy
        app: "app-trivy"
        component: redis
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 120
      containers:
      - name: redis
        image: docker.smart.mos.ru/library/goharbor/redis-photon:v2.6.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 1
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        heritage: Helm
        release: app
        chart: trivy
        app: "app-trivy"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "1Gi"
---
# Source: trivy/templates/trivy/trivy-sts.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-trivy
  namespace: trivy
  labels:
    heritage: Helm
    release: app
    chart: trivy
    app: "app-trivy"
    component: trivy
spec:
  replicas: 1
  serviceName: app-trivy
  selector:
    matchLabels:
      release: app
      app: "app-trivy"
      component: trivy
  template:
    metadata:
      labels:
        heritage: Helm
        release: app
        chart: trivy
        app: "app-trivy"
        component: trivy
      annotations:
        checksum/secret: 0b1ee7b98ca6f7972195e3c2336bccaf18faf6664b21c275912699eb700e545d
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      hostAliases:
      - ip: 10.43.114.232
        hostnames: 
        - "github.com"      
      containers:
        - name: trivy
          image: docker.smart.mos.ru/library/goharbor/trivy-adapter-photon:v2.6.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: "SCANNER_LOG_LEVEL"
              value: "info"
            - name: "SCANNER_TRIVY_CACHE_DIR"
              value: "/home/scanner/.cache/trivy"
            - name: "SCANNER_TRIVY_REPORTS_DIR"
              value: "/home/scanner/.cache/reports"
            - name: "SCANNER_TRIVY_DEBUG_MODE"
              value: "false"
            - name: "SCANNER_TRIVY_VULN_TYPE"
              value: "os,library"
            - name: "SCANNER_TRIVY_TIMEOUT"
              value: "5m0s"
            - name: "SCANNER_TRIVY_GITHUB_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: app-trivy
                  key: gitHubToken
            - name: "SCANNER_TRIVY_SEVERITY"
              value: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
            - name: "SCANNER_TRIVY_IGNORE_UNFIXED"
              value: "false"
            - name: "SCANNER_TRIVY_SKIP_UPDATE"
              value: "false"
            - name: "SCANNER_TRIVY_OFFLINE_SCAN"
              value: "true"
            - name: "SCANNER_TRIVY_INSECURE"
              value: "false"
            - name: SCANNER_API_SERVER_ADDR
              value: ":8080"
            - name: "SCANNER_REDIS_URL"
              valueFrom:
                secretKeyRef:
                  name: app-trivy
                  key: redisURL
            - name: "SCANNER_STORE_REDIS_URL"
              valueFrom:
                secretKeyRef:
                  name: app-trivy
                  key: redisURL
            - name: "SCANNER_JOB_QUEUE_REDIS_URL"
              valueFrom:
                secretKeyRef:
                  name: app-trivy
                  key: redisURL
          ports:
            - name: api-server
              containerPort: 8080
          volumeMounts:
          - name: data
            mountPath: /home/scanner/.cache
            readOnly: false
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /probe/healthy
              port: api-server
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /probe/ready
              port: api-server
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        heritage: Helm
        release: app
        chart: trivy
        app: "app-trivy"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "5Gi"
