apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "trivy.redis" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "trivy.labels" . | indent 4 }}
    component: redis
spec:
  replicas: 1
  serviceName: {{ template "trivy.redis" . }}
  selector:
    matchLabels:
{{ include "trivy.matchLabels" . | indent 6 }}
      component: redis
  template:
    metadata:
      labels:
{{ include "trivy.labels" . | indent 8 }}
        component: redis
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      automountServiceAccountToken: {{ .Values.redis.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      containers:
      - name: redis
        image: {{ .Values.redis.image.repository -}} : {{- .Values.redis.image.tag }}
        imagePullPolicy: {{ .Values.all.image.pullPolicy }}
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 1
          periodSeconds: 10
{{- if .Values.redis.resources }}
        resources:
{{ toYaml .Values.redis.resources | indent 10 }}
{{- end -}}