apiVersion: v1
kind: Service
metadata:
  name: {{ template "trivy.redis" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "trivy.labels" . | indent 4 }}
spec:
  ports:
    - port: 6379
  selector:
{{ include "trivy.matchLabels" . | indent 4 }}
    component: redis