{{- if eq .Values.redis.type "internal" -}}
{{- $redis := .Values.persistence.persistentVolumeClaim.redis -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "trivy.redis" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "trivy.labels" . | indent 4 }}
    component: redis
spec:
  replicas: 1
  serviceName: {{ template "trivy.redis" . }}
  selector:
    matchLabels:
{{ include "trivy.matchLabels" . | indent 6 }}
      component: redis
  template:
    metadata:
      labels:
{{ include "trivy.labels" . | indent 8 }}
        component: redis
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      automountServiceAccountToken: {{ .Values.redis.internal.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      containers:
      - name: redis
        image: {{ .Values.redis.internal.image.repository -}} : {{- .Values.redis.internal.image.tag }}
        imagePullPolicy: {{ .Values.all.image.pullPolicy }}
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 1
          periodSeconds: 10
{{- if .Values.redis.internal.resources }}
        resources:
{{ toYaml .Values.redis.internal.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
{{ include "trivy.labels" . | indent 8 }}
    spec:
      accessModes: [{{ $redis.accessMode | quote }}]
      resources:
        requests:
          storage: {{ $redis.size | quote }}
{{- end -}}
