{{ if .Values.trivy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "trivy.name" . }}"
  namespace: {{ .Values.namespace }}
  labels:
{{ include "trivy.labels" . | indent 4 }}
spec:
  type: {{ .Values.trivy.service.type }}
  ports:
    - name: {{ .Values.trivy.service.name }}
      protocol: {{ .Values.trivy.service.protocol }}
      port: {{ .Values.trivy.service.port }}
      {{- if eq .Values.trivy.service.type "NodePort" }}
      nodePort: {{ .Values.trivy.service.nodePort }}
      {{- end }}
  selector:
{{ include "trivy.matchLabels" . | indent 4 }}
    component: trivy
{{ end }}