{{- if .Values.trivy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trivy.name" . }}
  labels:
{{ include "trivy.labels" . | indent 4 }}
type: Opaque
data:
  redisURL: {{ include "trivy.redis.urlForTrivy" . | b64enc }}
  gitHubToken: {{  .Values.trivy.gitHubToken | default "" | b64enc | quote }}
{{- end }}
