---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.reverseProxy.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.reverseProxy.name -}} - {{- .Values.nameOverride }}
spec:
  replicas: {{ .Values.reverseProxy.replicas }}
  selector:
    matchLabels:
{{ include "trivy.matchLabels" . | indent 6 }}
      component: {{ .Values.reverseProxy.name }}
  template:
    metadata:
      labels:
{{ include "trivy.labels" . | indent 8 }}
        component: {{ .Values.reverseProxy.name }}
    spec:
      containers:
      - name: {{ .Values.reverseProxy.name }}
        image: {{ .Values.reverseProxy.image.repository -}} : {{- .Values.reverseProxy.image.tag }}
        imagePullPolicy: {{ .Values.all.image.pullPolicy }}
        ports:
        - containerPort:  {{ .Values.reverseProxy.port }}
          protocol: {{ .Values.reverseProxy.protocol }}
        env:
        - name: TZ
          value: {{ .Values.environments.timeZone }}