---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.reverseProxy.service.name }}-srv
  namespace: {{ .Values.namespace }}
spec:
  selector:
{{ include "trivy.matchLabels" . | indent 4 }}
    component: {{ .Values.reverseProxy.name }}
  ports:
  - name: {{ .Values.reverseProxy.name }}
    protocol: {{ .Values.reverseProxy.service.protocol }}
    port: {{ .Values.reverseProxy.service.port }}
    targetPort: {{ .Values.reverseProxy.port }}
  clusterIP: {{ .Values.reverseProxy.service.clusterIP }}